<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP" ignored="0" name="RetryMulitple" tests="14" failures="4" timestamp="२४ मार्च २०१८ ०६:३४:२३ GMT" time="0.251" errors="0">
  <testcase name="test1" time="0.037" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.004" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform.test1(RetryTestExecutionWithIAnnotationTransform.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.004" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform.test2(RetryTestExecutionWithIAnnotationTransform.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="com.retry.with.IAnnotation.transformer.RetryTestExecutionWithIAnnotationTransform"/>
  <testcase name="test4" time="0.003" classname="com.retry.with.IAnnotation.transformer.TestClass2">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.003" classname="com.retry.with.IAnnotation.transformer.TestClass2">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test4" time="0.003" classname="com.retry.with.IAnnotation.transformer.TestClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.retry.with.IAnnotation.transformer.TestClass2.test4(TestClass2.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.003" classname="com.retry.with.IAnnotation.transformer.TestClass2">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.005" classname="com.retry.with.IAnnotation.transformer.TestClass2">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.004" classname="com.retry.with.IAnnotation.transformer.TestClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.retry.with.IAnnotation.transformer.TestClass2.test5(TestClass2.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test6" time="0.005" classname="com.retry.with.IAnnotation.transformer.TestClass2"/>
</testsuite> <!-- RetryMulitple -->
